name: mask_agcrn_pems # same with dataloader file name
data_path: data/processed/pems-63_296-3_447-2-12_12_C.npz

dataset_name: mask_pems
batch_size: 64 
seed: 47
device: cuda
scaler: standard
incre_num: 2
is_last: False
is_default_graph: False
is_norm_loss: False
is_norm_metric: False
is_mask_loss: True
is_cons_loss: False
is_oracle: False
is_col: True
use_norm: False

model_name: agcrn
num_nodes: 447
first_num_nodes: 296
embed_dim: 40
input_dim: 1
output_dim: 1
lag: 12
horizon: 12

rnn_units: 64
num_layers: 2
cheb_k: 2
dropout: 0.2

skip_epoch: 1
optimizer: adam
loss_func: mae
lr_decay: False
lr_decay_rate: 0.3
lr_decay_step: [5,20,40,70]
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
teacher_forcing: False
grad_norm: False

log_path: main.log
log_step: 20

mae_thresh: None
mape_thresh: None