name: mask_informer_electricity # same with dataloader file name
data_path: data/processed/elc-925_261-7_321-3_321-12_12_C.npz

dataset_name: mask_electricity 
batch_size: 64
seed: 47
device: cuda
scaler: standard
incre_num: 2
is_last: False
is_default_graph: False
is_norm_loss: True
is_norm_metric: True
is_mask_loss: True
is_cons_loss: False
is_oracle: False
is_col: True
use_norm: True

model_name: Informer
num_nodes: 321
first_num_nodes: 261
input_dim: 1
output_dim: 1
enc_in: 321
dec_in: 321
c_out: 321
lag: 12
horizon: 12
label_len: 6
pred_len: 12
output_attention: False


e_layers: 4
d_model: 512
d_ff: 512
freq: h
embed: timeF
dropout: 0.1
factor: 1
n_heads: 8
activation: gelu
embed_type: 3
distil: False
d_layers: 1


skip_epoch: 1
optimizer: adam
loss_func: mae
lr_decay: True
lr_decay_rate: 0.3
lr_decay_step: [5,20,40,70]
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
teacher_forcing: False
grad_norm: False

log_path: main.log
log_step: 20

mae_thresh: None
mape_thresh: None