name: mask_msgnet_pems # same with dataloader file name
data_path: data/processed/pems-63_447-3_447-2-12_12_C_Oracle.npz

dataset_name: mask_pems
batch_size: 64 
seed: 47
device: cuda
scaler: standard
incre_num: 2
is_last: False
is_default_graph: False
is_norm_loss: False
is_norm_metric: False
is_mask_loss: False
is_cons_loss: False
is_oracle: True
is_col: True
use_norm: False

model_name: msgnet
num_nodes: 447
first_num_nodes: 296
input_dim: 1
rnn_units: 64
mlp_size: 64
output_dim: 1
horizon: 12
lag: 12
e_layers: 2
enc_in: 447
dec_in: 447
d_model: 512
embed: timeF
freq: h
c_out: 447
individual: False
top_k: 5
d_ff: 2048
n_heads: 8
conv_channel: 32
skip_channel: 32
gcn_depth: 2
propalpha: 0.3
node_dim: 20
num_node: 447 
dropout: 0.2

skip_epoch: 1
optimizer: adam
loss_func: mae
lr_decay: False
lr_decay_rate: 0.3
lr_decay_step: [5,20,40,70]
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
teacher_forcing: False
grad_norm: False

log_path: main.log
log_step: 20

mae_thresh: None
mape_thresh: None