name: uni_patchtst_electricity # same with dataloader file name
data_path: data/processed/elc-925_261-7_321-3_321-12_12_C.npz

dataset_name: uni_electricity 
# batch_size: 64
batch_size: 1440
seed: 47
device: cuda
scaler: standard
incre_num: 2
is_last: False
is_default_graph: False
is_norm_loss: True
is_norm_metric: True
is_mask_loss: True
is_cons_loss: False
is_oracle: False
is_col: True
use_norm: True
cl_loss_weight: 0
first_feats: 261

model_name: PatchTST
model_cfg:
  fc_dropout: 0.05
  head_dropout: 0.0
  # patch_len: 16
  patch_len: 4
  stride: 2
  padding_patch: end
  revin: 1
  affine: 0
  subtract_last: 0
  decomposition: 0
  kernel_size: 25
  individual: 0
  embed_type: 0
  # enc_in: 7
  # dec_in: 7
  # c_out: 7
  d_model: 512
  n_heads: 8
  e_layers: 2
  d_layers: 1
  d_ff: 2048
  moving_avg: 25
  factor: 1
  distil: true
  dropout: 0.05
  embed: timeF
  activation: gelu
  output_attention: false
  do_predict: false
  #
  # num_nodes: 321
  num_nodes: 1
  first_num_nodes: 261
  input_dim: 1
  output_dim: 1
  lag: 12
  horizon: 12
  label_len: 6

num_nodes: 321
first_num_nodes: 261
input_dim: 1
output_dim: 1
lag: 12
horizon: 12
label_len: 6



skip_epoch: 1
optimizer: adam
loss_func: mae
lr_decay: True
lr_decay_rate: 0.3
lr_decay_step: [5,20,40,70]
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
teacher_forcing: False
grad_norm: False

log_path: main.log
log_step: 20

mae_thresh: None
mape_thresh: None