name: pyg_weather # same with dataloader file name
data_path: data/processed/weather-560_310-7_410-3_410-12_12_C.npz

dataset_name: pyg_electricity
batch_size: 8
log_path: main.log
seed: 47
device: cuda
scaler: standard

is_norm_metric: False
is_norm_loss: True
is_col: True
use_norm: True
is_pregraph: False
is_cons_loss: False
augment_data: False

model_name: dyngraphwave
max_nodes: 410
first_feats: 310
node_embed: 40
input_size: 1
output_size: 1
hidden_size: 64
horizon: 12
num_layers: 2
dropout: 0.2
weight: 0.5

skip_epoch: 1
optimizer: adam
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
augementation_rate: 0
