name: pyg_pems # same with dataloader file name
data_path: data/processed/pems-63_296-3_447-2-12_12_C.npz

dataset_name: pyg_electricity
batch_size: 8
log_path: main.log
seed: 47
device: cuda
scaler: standard

is_norm_metric: False
is_norm_loss: False
is_col: True
use_norm: False
is_pregraph: False
is_cons_loss: True
weight: 0.3
temperature: 0.1
cl_loss_weight: 1.0
augment_data: False
is_over_sampling: False
dynamic: True

model_name: dyngraphwave
max_nodes: 447
first_feats: 296
node_embed: 20
input_size: 1
output_size: 1
hidden_size: 64
horizon: 12
num_layers: 2
dropout: 0.2

kernel_size: 2
residual_channels: 32
end_channels: 512
skip_channels: 256
dilation_channels: 32

skip_epoch: 1
optimizer: adam
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
augementation_rate: 0
