name: uni_pems
data_path: data/processed/pems-63_296-3_447-2-12_12_C.npz

dataset_name: uni_electricity 
batch_size: 2048
log_path: main.log 
seed: 47
device: cuda
scaler: standard
is_first_period_only: False
is_norm_metric: False
is_norm_loss: False
is_col: True

model_name: gru
input_dim: 1
output_dim: 1
lag: 12
horizon: 12
rnn_units: 64
num_layers: 2

input_size: 12
output_size: 12

skip_epoch: 1
optimizer: adam
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10

first_feats: 296

augementation_rate: 0
augement_all: False