name: pyg_weather # same with dataloader file name
data_path: data/processed/weather-560_310-7_410-3_410-12_12_C.npz

dataset_name: pyg_electricity
batch_size: 32
log_path: main.log
seed: 47
device: cuda
scaler: standard

is_norm_metric: False
is_norm_loss: True
is_col: True
use_norm: True
is_pregraph: False
is_cons_loss: False
augment_data: False
is_gpt: True
model_name: GPT4TS
max_nodes: 410
first_feats: 310
freeze: True
input_size: 12
itr: 3
patch_size: 4
pretrain: True
output_size: 12
is_over_sampling: False
stride: 8
gpt_layers: 6
d_model: 768
hidden_size: 128
num_layers: 3
dropout: 0.2
cl_loss_weight: 1.0

skip_epoch: 1
optimizer: adam
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10
augementation_rate: 0
