name: uni_pems
data_path: data/processed/pems-63_296-3_447-2-12_12.npz

dataset_name: uni_electricity 
batch_size: 2048
log_path: main.log 
seed: 47
device: cuda
scaler: standard
is_first_period_only: False
is_norm_metric: False
is_norm_loss: False
is_col: False

model_name: mlp
input_size: 12
output_size: 12
hidden_size: 128
num_layers: 3
dropout: 0.2

skip_epoch: 1
optimizer: adam
lr: 0.001
weight_decay: 0.0
epochs: 100

early_stoping: True
patience: 10

first_feats: 296

augementation_rate: 0
augement_all: False